### ISSUE TITLE
SDK 使用告知

### ISSUE THREAD

**Issue by qige-one** [qige-one/mixin_java_sdk#2]
你好！
如果你使用了本 Java SDK，请在下面跟帖回复你的 Mixin 机器人 id，我将登记到本 SDK 首页的说明里，thanks!

**Comment by wenewzhang** [comment]
我想写一个，但是，
这个环境怎么搭建？

**Comment by wenewzhang** [comment]
看来这个用的是maven,我打算用gradle移植你的代码

**Comment by wenewzhang** [comment]
mvn exec:java -Dexec.mainClass="one.mixin.api.MixinBotDemo"
出错如下：
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ sdk ---
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at one.mixin.api.PrivateKeyReader.getPrivateKey(PrivateKeyReader.java:100)
	at one.mixin.api.Config.loadPrivateKey(Config.java:25)
	at one.mixin.api.Config.<clinit>(Config.java:34)
	at one.mixin.api.MixinUtil$JWTTokenGen.genToken(MixinUtil.java:53)
	at one.mixin.api.MixinUtil$JWTTokenGen.genToken(MixinUtil.java:35)
	at one.mixin.api.MixinBot.connectToRemoteMixin(MixinBot.java:16)
	at one.mixin.api.MixinBotDemo.main(MixinBotDemo.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jabreuint** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
DannyAhmedApex, @superhpr, @rocjiang, @includeleec, @ongardevs, @w950888, @kyokokiss, @rongliangduan, @kingideayou, @kk2018, @wujiulin, @zhdhr0000, @joyoyao, @anosajib, @nfsc-tommy, @PolGomezWM, @SeniorZhai, @xboy-im, @mcxinyu, @harryzhicheng

**Comment by bren-wood** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
atsumo, @vamischenko, @liderxlt, @Kim-Lee, @perlman-fun, @dc365, @iaminstanceof, @qdriven, @liujian8856, @Zrocky, @willwl, @jack-ylt, @fanturbo, @Zegele, @BestDI, @1105306364, @dmtrki, @mqentar, @doitlite, @Mykola-Kryvyi
